version: '3.1'

services:

  app:
    build: .
    container_name: scraper-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: admin
      DATABASE_USER: mongo
      DATABASE_PASS: mongo-user-pass
      APP_FOLLOW_TOPICS: '["trump","isis","esports","lady gaga"]'
      TWITTER_API_KEY: 'XlqBn5Hpuvvd0j2dlZTJH0Nzs'
      TWITTER_API_SECRET: 'vzSlioQ2fr84IYhzqNIbgbSoibbif0r5Wp87WXt2ZOjtVCDmKE'
      #TWITTER_API_KEY=...put api key here and uncomment it
      #TWITTER_API_SECRET=...put api secret and uncomment this one too
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: tweetsdb
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo-user-pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo-user-pass
